import {
  FLOOR2_CAVE_SYSTEM_DEFAULTS,
  FLOOR2_STAIRS_POPPED_GOAL_ID,
  FLOOR2_TERRITORY_FAMILY_SPAWN_SHARE,
  FLOOR2_TERRITORY_NEUTRAL_SPAWN_SHARE,
  FLOOR2_VICTORY_GOAL_ID,
  bossDefeatGoalId,
  buildDenUnlockQuestPack,
  findBossDenRoom,
  floor2EnemyDirectorSystem,
  floor2ObjectiveTick,
  getQuadrantForPosition,
  getQuadrantSpawnWeights,
  initializeFloor2Bosses,
  isDenUnlocked,
  isFamilySpawnGated,
  markDenUnlocked,
  resolveFloor2ArchetypeAIType,
  resolveAmbientFamilyIndex,
  resolveFloor2TrashSpawnWeights,
  selectDenUnlockObjectives,
  spawnFamilyBoss,
} from './floor2Scenario.js';

const floor2ScenarioTestSeams = {
  FLOOR2_TERRITORY_FAMILY_SPAWN_SHARE,
  FLOOR2_TERRITORY_NEUTRAL_SPAWN_SHARE,
  resolveFloor2ArchetypeAIType,
  FLOOR2_CAVE_SYSTEM_DEFAULTS,
  FLOOR2_VICTORY_GOAL_ID,
  FLOOR2_STAIRS_POPPED_GOAL_ID,
  bossDefeatGoalId,
  selectDenUnlockObjectives,
  buildDenUnlockQuestPack,
  findBossDenRoom,
  spawnFamilyBoss,
  initializeFloor2Bosses,
  floor2ObjectiveTick,
  isFamilySpawnGated,
  isDenUnlocked,
  markDenUnlocked,
  getQuadrantForPosition,
  getQuadrantSpawnWeights,
  resolveFloor2TrashSpawnWeights,
  resolveAmbientFamilyIndex,
  floor2EnemyDirectorSystem,
};

export default floor2ScenarioTestSeams;
