apiVersion: goobers.dev/v1alpha1
kind: Manifest
metadata:
  name: crawler-goobers
spec:
  instance:
    name: crawler
    environment: dev
  connections:
    - name: repo-token
      type: repo
      provider: github
      secretRef:
        name: repo-token
  gaggles:
    - example
