export type AbilityPresentationKind = 'active' | 'passive' | 'spell';
export type AbilityPresentationCategory = 'combat' | 'defense' | 'utility';

export interface AbilityPresentation {
  readonly id: string;
  readonly name: string;
  readonly shortLabel: string;
  readonly description: string;
  readonly category: AbilityPresentationCategory;
  readonly kind: AbilityPresentationKind;
  readonly iconBriefId?: string;
  readonly cooldownFrames?: number;
  readonly passiveEffectSummary?: string;
  readonly passiveRequirementSummary?: string;
}

export const ABILITY_PRESENTATION_BY_ID = {
  'battle-focus': {
    id: 'battle-focus',
    name: 'Battle Focus',
    shortLabel: 'FOCUS',
    description: 'Land enough hits to convert momentum into damage.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 30,
    iconBriefId: 'ability-icon-battle-focus',
  },
  'veteran-instinct': {
    id: 'veteran-instinct',
    name: 'Veteran Instinct',
    shortLabel: 'VETERAN',
    description: 'Constant battlefield awareness improves your armor and pickup range.',
    category: 'defense',
    kind: 'passive',
    iconBriefId: 'ability-icon-veteran-instinct',
  },
  'combat-flow': {
    id: 'combat-flow',
    name: 'Combat Flow',
    shortLabel: 'C.FLOW',
    description:
      'Sustained combat discipline yields permanent damage and attack-speed improvements.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +5%, Attack Speed +5%',
    iconBriefId: 'ability-icon-combat-flow',
  },
  'stalwart-resolve': {
    id: 'stalwart-resolve',
    name: 'Stalwart Resolve',
    shortLabel: 'STALWRT',
    description: 'Battle scars calcify into permanent armor and max HP.',
    category: 'defense',
    kind: 'passive',
    passiveEffectSummary: 'Armor +3, Max HP +15',
    iconBriefId: 'ability-icon-stalwart-resolve',
  },
  'ever-vigilant': {
    id: 'ever-vigilant',
    name: 'Ever Vigilant',
    shortLabel: 'VIGILANT',
    description: 'Constant evasion sharpens reflexes into a permanent speed advantage.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Move Speed +15%',
    iconBriefId: 'ability-icon-ever-vigilant',
  },
  'blade-mastery': {
    id: 'blade-mastery',
    name: 'Blade Mastery',
    shortLabel: 'BLADE',
    description: 'Bonus damage and accuracy while a slashing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%, Accuracy +0.05',
    passiveRequirementSummary: 'a slashing weapon',
    iconBriefId: 'ability-icon-blade-mastery',
  },
  'vital-targeting': {
    id: 'vital-targeting',
    name: 'Vital Targeting',
    shortLabel: 'VITAL',
    description: 'Bonus damage while a stabbing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%',
    passiveRequirementSummary: 'a stabbing weapon',
    iconBriefId: 'ability-icon-vital-targeting',
  },
  'brute-force': {
    id: 'brute-force',
    name: 'Brute Force',
    shortLabel: 'BRUTE',
    description: 'Bonus damage and armor while a smashing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%, Armor +2',
    passiveRequirementSummary: 'a smashing weapon',
    iconBriefId: 'ability-icon-brute-force',
  },
  'marksmans-eye': {
    id: 'marksmans-eye',
    name: "Marksman's Eye",
    shortLabel: 'MARKS',
    description: 'Bonus accuracy and projectile speed while a ranged weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Projectile Speed +10%',
    passiveRequirementSummary: 'a ranged weapon',
    iconBriefId: 'ability-icon-marksmans-eye',
  },
  'rapid-release': {
    id: 'rapid-release',
    name: 'Rapid Release',
    shortLabel: 'RAPID',
    description: 'Bonus attack speed while a throwing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Attack Speed +20%',
    passiveRequirementSummary: 'a throwing weapon',
  },
  'iron-resolve': {
    id: 'iron-resolve',
    name: 'Iron Resolve',
    shortLabel: 'IRON',
    description: 'Bonus damage while a forearms weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a forearms weapon',
  },
  'arcane-efficiency': {
    id: 'arcane-efficiency',
    name: 'Arcane Efficiency',
    shortLabel: 'ARCANE',
    description: 'Bonus damage while an arcane weapon is equipped.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'an arcane weapon',
  },
  'keen-swordsman': {
    id: 'keen-swordsman',
    name: 'Keen Swordsman',
    shortLabel: 'KEEN',
    description: 'Bonus accuracy and damage while a sword is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Damage +8%',
    passiveRequirementSummary: 'a sword',
  },
  shadowblade: {
    id: 'shadowblade',
    name: 'Shadowblade',
    shortLabel: 'SHADOW',
    description: 'Significant damage bonus while a dagger is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +20%',
    passiveRequirementSummary: 'a dagger',
  },
  'crushing-momentum': {
    id: 'crushing-momentum',
    name: 'Crushing Momentum',
    shortLabel: 'CRUSH',
    description: 'Bonus damage while a hammer is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%',
    passiveRequirementSummary: 'a hammer',
  },
  'athletes-grit': {
    id: 'athletes-grit',
    name: "Athlete's Grit",
    shortLabel: 'GRIT',
    description: 'Bonus accuracy and armor while sports equipment is equipped.',
    category: 'defense',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Armor +2',
    passiveRequirementSummary: 'sports equipment',
  },
  'archers-stance': {
    id: 'archers-stance',
    name: "Archer's Stance",
    shortLabel: 'ARCHER',
    description: 'Bonus accuracy while a bow is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1',
    passiveRequirementSummary: 'a bow',
  },
  'precision-bolts': {
    id: 'precision-bolts',
    name: 'Precision Bolts',
    shortLabel: 'PRECISE',
    description: 'Bonus damage while a crossbow is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a crossbow',
  },
  'hair-trigger': {
    id: 'hair-trigger',
    name: 'Hair Trigger',
    shortLabel: 'TRIGGER',
    description: 'Bonus attack speed while a pistol is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Attack Speed +20%',
    passiveRequirementSummary: 'a pistol',
  },
  'juggling-arsenal': {
    id: 'juggling-arsenal',
    name: 'Juggling Arsenal',
    shortLabel: 'JUGGLE',
    description: 'Extra projectile while throwing weapons are equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: '+1 projectile',
    passiveRequirementSummary: 'throwing weapons',
  },
  'bare-knuckle': {
    id: 'bare-knuckle',
    name: 'Bare Knuckle',
    shortLabel: 'KNUCKLE',
    description: 'Bonus damage while unarmed.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'no weapon (unarmed)',
  },
  'arcane-attunement': {
    id: 'arcane-attunement',
    name: 'Arcane Attunement',
    shortLabel: 'ARCANE',
    description: 'Bonus damage while a spellcraft weapon is equipped.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a spellcraft weapon',
  },
  fireball: {
    id: 'fireball',
    name: 'Fire Wand',
    shortLabel: 'FIRE',
    description: 'Hurl a ball of fire that explodes in an area, burning enemies.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-fireball',
    cooldownFrames: 300,
  },
  heal: {
    id: 'heal',
    name: 'Heal',
    shortLabel: 'HEAL',
    description: 'Mend your wounds with restorative magic.',
    category: 'defense',
    kind: 'spell',
    iconBriefId: 'ability-icon-heal',
    cooldownFrames: 1800,
  },
  'pulse-shield': {
    id: 'pulse-shield',
    name: 'Pulse Shield',
    shortLabel: 'PULSE',
    description: 'Release a protective shockwave that knocks back nearby enemies.',
    category: 'defense',
    kind: 'spell',
    iconBriefId: 'ability-icon-pulse-shield',
    cooldownFrames: 1200,
  },
  'magic-missile': {
    id: 'magic-missile',
    name: 'Magic Missile',
    shortLabel: 'MISSILE',
    description: 'Launch a precise arcane bolt into the nearest enemy.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-magic-missile',
    cooldownFrames: 180,
  },
  'frost-nova': {
    id: 'frost-nova',
    name: 'Frost Nova',
    shortLabel: 'FROST',
    description: 'Burst freezing magic around you, damaging and slowing nearby foes.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-frost-nova',
    cooldownFrames: 900,
  },
  bless: {
    id: 'bless',
    name: 'Bless',
    shortLabel: 'BLESS',
    description: 'Call down a brief blessing that sharpens your strikes and footwork.',
    category: 'utility',
    kind: 'spell',
    iconBriefId: 'ability-icon-bless',
    cooldownFrames: 1200,
  },
  stoneskin: {
    id: 'stoneskin',
    name: 'Stoneskin',
    shortLabel: 'STONE',
    description: 'Harden your flesh into living granite for a few desperate moments.',
    category: 'defense',
    kind: 'spell',
    iconBriefId: 'ability-icon-stoneskin',
    cooldownFrames: 1500,
  },
  curse: {
    id: 'curse',
    name: 'Curse',
    shortLabel: 'CURSE',
    description: 'Blight a cluster of enemies, dragging their movement into a crawl.',
    category: 'utility',
    kind: 'spell',
    iconBriefId: 'ability-icon-curse',
    cooldownFrames: 840,
  },
  'vampiric-touch': {
    id: 'vampiric-touch',
    name: 'Vampiric Touch',
    shortLabel: 'VAMP',
    description: 'Rip vitality from the nearest foe and pour it back into yourself.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-vampiric-touch',
    cooldownFrames: 720,
  },
  haste: {
    id: 'haste',
    name: 'Haste',
    shortLabel: 'HASTE',
    description: 'Flood your limbs with quicksilver speed after a strong damage spike.',
    category: 'utility',
    kind: 'spell',
    iconBriefId: 'ability-icon-haste',
    cooldownFrames: 1080,
  },
  // Weapon class passives (14 total)
  'slashing-mastery-base': {
    id: 'slashing-mastery-base',
    name: 'Slashing Mastery',
    shortLabel: 'SLASH',
    description: 'Bonus damage while wielding slashing weapons.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a slashing weapon',
  },
  'slashing-mastery-evolved': {
    id: 'slashing-mastery-evolved',
    name: 'Slashing Mastery (Evolved)',
    shortLabel: 'SLASH+',
    description: 'Advanced slashing technique. Increased damage bonus.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%',
    passiveRequirementSummary: 'a slashing weapon',
  },
  'stabbing-precision-base': {
    id: 'stabbing-precision-base',
    name: 'Stabbing Precision',
    shortLabel: 'STAB',
    description: 'Bonus attack speed while wielding stabbing weapons.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Attack Speed +10%',
    passiveRequirementSummary: 'a stabbing weapon',
  },
  'stabbing-precision-evolved': {
    id: 'stabbing-precision-evolved',
    name: 'Stabbing Precision (Evolved)',
    shortLabel: 'STAB+',
    description: 'Refined stabbing technique. Increased attack speed.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Attack Speed +15%',
    passiveRequirementSummary: 'a stabbing weapon',
  },
  'smashing-force-base': {
    id: 'smashing-force-base',
    name: 'Smashing Force',
    shortLabel: 'SMASH',
    description: 'Bonus pickup range and damage while wielding smashing weapons.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Pickup Range +0.75, Damage +5%',
    passiveRequirementSummary: 'a smashing weapon',
  },
  'smashing-force-evolved': {
    id: 'smashing-force-evolved',
    name: 'Smashing Force (Evolved)',
    shortLabel: 'SMASH+',
    description: 'Uncontrolled smashing power. Increased range and damage.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Pickup Range +1.0, Damage +8%',
    passiveRequirementSummary: 'a smashing weapon',
  },
  'ranged-marksmanship-base': {
    id: 'ranged-marksmanship-base',
    name: 'Ranged Marksmanship',
    shortLabel: 'MARKS',
    description: 'Bonus accuracy while wielding ranged weapons.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1',
    passiveRequirementSummary: 'a ranged weapon',
  },
  'ranged-marksmanship-evolved': {
    id: 'ranged-marksmanship-evolved',
    name: 'Ranged Marksmanship (Evolved)',
    shortLabel: 'MARKS+',
    description: 'Expert ranged technique. Significantly improved accuracy.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.15',
    passiveRequirementSummary: 'a ranged weapon',
  },
  'throwing-trajectory-base': {
    id: 'throwing-trajectory-base',
    name: 'Throwing Trajectory',
    shortLabel: 'THROW',
    description: 'Bonus projectile speed while wielding throwing weapons.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Projectile Speed +10%',
    passiveRequirementSummary: 'throwing weapons',
  },
  'throwing-trajectory-evolved': {
    id: 'throwing-trajectory-evolved',
    name: 'Throwing Trajectory (Evolved)',
    shortLabel: 'THROW+',
    description: 'Perfected throwing arc. Dramatically increased projectile speed.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Projectile Speed +15%',
    passiveRequirementSummary: 'throwing weapons',
  },
  'forearms-brawler-base': {
    id: 'forearms-brawler-base',
    name: 'Forearms Brawler',
    shortLabel: 'BRAWL',
    description: 'Bonus accuracy and damage while wielding forearm weapons.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Damage +5%',
    passiveRequirementSummary: 'a forearm weapon',
  },
  'forearms-brawler-evolved': {
    id: 'forearms-brawler-evolved',
    name: 'Forearms Brawler (Evolved)',
    shortLabel: 'BRAWL+',
    description: 'Master brawler instinct. Superior accuracy and power.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.15, Damage +8%',
    passiveRequirementSummary: 'a forearm weapon',
  },
  'arcane-power-base': {
    id: 'arcane-power-base',
    name: 'Arcane Power',
    shortLabel: 'ARCANE',
    description: 'Bonus accuracy and arcane attunement while wielding arcane weapons.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Arcane Regen +5%',
    passiveRequirementSummary: 'an arcane weapon',
  },
  'arcane-power-evolved': {
    id: 'arcane-power-evolved',
    name: 'Arcane Power (Evolved)',
    shortLabel: 'ARCANE+',
    description: 'Channeled arcane mastery. Heightened focus and arcane flow.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.15, Arcane Regen +8%',
    passiveRequirementSummary: 'an arcane weapon',
  },
  // Weapon type actives (20 total)
  'sword-strike-base': {
    id: 'sword-strike-base',
    name: 'Sword Strike',
    shortLabel: 'STRIKE',
    description: 'Slash nearby enemies with your sword.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'sword-riposte': {
    id: 'sword-riposte',
    name: 'Riposte',
    shortLabel: 'RIPOST',
    description: 'Quick counterattack when health is low.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 480,
  },
  'sword-strike-evolved': {
    id: 'sword-strike-evolved',
    name: 'Sword Strike (Evolved)',
    shortLabel: 'STRIKE+',
    description: 'Devastate nearby enemies with an enhanced slash.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'sword-mortal-strike': {
    id: 'sword-mortal-strike',
    name: 'Mortal Strike',
    shortLabel: 'MORTAL',
    description: 'Powerful counter with guaranteed critical hit.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 600,
  },
  'dagger-rapid-base': {
    id: 'dagger-rapid-base',
    name: 'Rapid Strikes',
    shortLabel: 'RAPID',
    description: 'Quick succession of dagger thrusts.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 240,
  },
  'dagger-poison': {
    id: 'dagger-poison',
    name: 'Poison Strike',
    shortLabel: 'POISON',
    description: 'Coat your blade with toxin for lasting damage.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 600,
  },
  'dagger-rapid-evolved': {
    id: 'dagger-rapid-evolved',
    name: 'Rapid Strikes (Evolved)',
    shortLabel: 'RAPID+',
    description: 'Blinding flurry of dagger strikes.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 240,
  },
  'dagger-deathmark': {
    id: 'dagger-deathmark',
    name: 'Deathmark',
    shortLabel: 'DEATH',
    description: 'Instant assassin strike marked for death.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 720,
  },
  'hammer-slam-base': {
    id: 'hammer-slam-base',
    name: 'Hammer Slam',
    shortLabel: 'SLAM',
    description: 'Crush nearby enemies with your hammer.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 480,
  },
  'hammer-whirlwind': {
    id: 'hammer-whirlwind',
    name: 'Whirlwind',
    shortLabel: 'WHIRL',
    description: 'Spin with your hammer, hitting all nearby enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 540,
  },
  'hammer-slam-evolved': {
    id: 'hammer-slam-evolved',
    name: 'Hammer Slam (Evolved)',
    shortLabel: 'SLAM+',
    description: 'Tremendous blow that stuns multiple enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 480,
  },
  'hammer-earthquake': {
    id: 'hammer-earthquake',
    name: 'Earthquake',
    shortLabel: 'QUAKE',
    description: 'Ground-shattering hammer strike affecting a wide area.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 720,
  },
  'bow-piercing-base': {
    id: 'bow-piercing-base',
    name: 'Piercing Shot',
    shortLabel: 'PIERCE',
    description: 'Fire an arrow that pierces through enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'bow-multishot': {
    id: 'bow-multishot',
    name: 'Multishot',
    shortLabel: 'MULTI',
    description: 'Fire multiple arrows at once.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 600,
  },
  'bow-piercing-evolved': {
    id: 'bow-piercing-evolved',
    name: 'Piercing Shot (Evolved)',
    shortLabel: 'PIERCE+',
    description: 'Powerful arrow that pierces multiple foes.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'bow-rain-of-arrows': {
    id: 'bow-rain-of-arrows',
    name: 'Rain of Arrows',
    shortLabel: 'RAIN',
    description: 'Rain arrows down on an area, hitting all enemies within.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 720,
  },
  'crossbow-bolt-base': {
    id: 'crossbow-bolt-base',
    name: 'Bolt Shot',
    shortLabel: 'BOLT',
    description: 'Fire a crossbow bolt at nearby enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 300,
  },
  'crossbow-ricochet': {
    id: 'crossbow-ricochet',
    name: 'Ricochet',
    shortLabel: 'BOUNCE',
    description: 'Fire bolts that bounce between enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 480,
  },
  'crossbow-bolt-evolved': {
    id: 'crossbow-bolt-evolved',
    name: 'Bolt Shot (Evolved)',
    shortLabel: 'BOLT+',
    description: 'Rapid-fire crossbow bolts hitting multiple targets.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 300,
  },
  'crossbow-piercing-volley': {
    id: 'crossbow-piercing-volley',
    name: 'Piercing Volley',
    shortLabel: 'VOLLEY',
    description: 'Barrage of armor-piercing bolts.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 660,
  },
  'pistol-shot-base': {
    id: 'pistol-shot-base',
    name: 'Pistol Shot',
    shortLabel: 'SHOT',
    description: 'Fire a quick pistol round at nearby enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 240,
  },
  'pistol-rapid-fire': {
    id: 'pistol-rapid-fire',
    name: 'Rapid Fire',
    shortLabel: 'FIRE',
    description: 'Unleash rapid gunfire.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 420,
  },
  'pistol-shot-evolved': {
    id: 'pistol-shot-evolved',
    name: 'Pistol Shot (Evolved)',
    shortLabel: 'SHOT+',
    description: 'Precise gunfire hitting multiple targets.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 240,
  },
  'pistol-barrage': {
    id: 'pistol-barrage',
    name: 'Barrage',
    shortLabel: 'BARRAGE',
    description: 'Continuous stream of pistol fire.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 720,
  },
  'throwing-toss-base': {
    id: 'throwing-toss-base',
    name: 'Throwing Toss',
    shortLabel: 'TOSS',
    description: 'Throw weapons at nearby enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 300,
  },
  'throwing-boomerang': {
    id: 'throwing-boomerang',
    name: 'Boomerang',
    shortLabel: 'BOOM',
    description: 'Throw a returning projectile that hits on return.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 480,
  },
  'throwing-toss-evolved': {
    id: 'throwing-toss-evolved',
    name: 'Throwing Toss (Evolved)',
    shortLabel: 'TOSS+',
    description: 'Rapid throwing strikes at multiple enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 300,
  },
  'throwing-scatter': {
    id: 'throwing-scatter',
    name: 'Scatter',
    shortLabel: 'SCATTER',
    description: 'Scatter throw weapons in all directions.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 600,
  },
  'unarmed-strike-base': {
    id: 'unarmed-strike-base',
    name: 'Unarmed Strike',
    shortLabel: 'PUNCH',
    description: 'Strike nearby enemies with your fists.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 240,
  },
  'unarmed-combo': {
    id: 'unarmed-combo',
    name: 'Combo',
    shortLabel: 'COMBO',
    description: 'Execute a rapid combo of punches and kicks.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'unarmed-strike-evolved': {
    id: 'unarmed-strike-evolved',
    name: 'Unarmed Strike (Evolved)',
    shortLabel: 'PUNCH+',
    description: 'Powerful strikes hitting multiple enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 240,
  },
  'unarmed-whirlwind-kick': {
    id: 'unarmed-whirlwind-kick',
    name: 'Whirlwind Kick',
    shortLabel: 'KICK',
    description: 'Spinning kick that hits all nearby enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 600,
  },
  'spell-bolt-base': {
    id: 'spell-bolt-base',
    name: 'Spell Bolt',
    shortLabel: 'BOLT',
    description: 'Cast a bolt of magical energy.',
    category: 'utility',
    kind: 'spell',
    cooldownFrames: 300,
  },
  'spell-chain': {
    id: 'spell-chain',
    name: 'Chain Lightning',
    shortLabel: 'CHAIN',
    description: 'Cast lightning that chains between enemies.',
    category: 'utility',
    kind: 'spell',
    cooldownFrames: 480,
  },
  'spell-bolt-evolved': {
    id: 'spell-bolt-evolved',
    name: 'Spell Bolt (Evolved)',
    shortLabel: 'BOLT+',
    description: 'Powerful magical bolts hitting multiple targets.',
    category: 'utility',
    kind: 'spell',
    cooldownFrames: 300,
  },
  'spell-meteor': {
    id: 'spell-meteor',
    name: 'Meteor',
    shortLabel: 'METEOR',
    description: 'Call down meteors on an area.',
    category: 'utility',
    kind: 'spell',
    cooldownFrames: 720,
  },
  'sports-swing-base': {
    id: 'sports-swing-base',
    name: 'Sports Swing',
    shortLabel: 'SWING',
    description: 'Swing sports equipment at nearby enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'sports-home-run': {
    id: 'sports-home-run',
    name: 'Home Run',
    shortLabel: 'HOMER',
    description: 'Powerful swing when health is low.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 540,
  },
  'sports-swing-evolved': {
    id: 'sports-swing-evolved',
    name: 'Sports Swing (Evolved)',
    shortLabel: 'SWING+',
    description: 'Devastating swing hitting multiple enemies.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 360,
  },
  'sports-grand-slam': {
    id: 'sports-grand-slam',
    name: 'Grand Slam',
    shortLabel: 'SLAM',
    description: 'Ultimate sports swing - a crowd-pleaser.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 720,
  },
  // Placeholder abilities for generic skills (L10, L15, L20 milestones)
  'placeholder-generic-l10': {
    id: 'placeholder-generic-l10',
    name: 'Intermediate Mastery',
    shortLabel: 'INTER',
    description: 'Placeholder for L10 milestone abilities (to be implemented).',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'TBD',
  },
  'placeholder-generic-l15': {
    id: 'placeholder-generic-l15',
    name: 'Advanced Mastery',
    shortLabel: 'ADV',
    description: 'Placeholder for L15 milestone abilities (to be implemented).',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'TBD',
  },
  'placeholder-generic-l20': {
    id: 'placeholder-generic-l20',
    name: 'Ultimate Mastery',
    shortLabel: 'ULT',
    description: 'Placeholder for L20 milestone abilities (to be implemented).',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'TBD',
  },
} as const satisfies Readonly<Record<string, AbilityPresentation>>;

export function getAbilityPresentation(id: string): AbilityPresentation | undefined {
  return (ABILITY_PRESENTATION_BY_ID as Readonly<Record<string, AbilityPresentation>>)[id];
}
