export type AbilityPresentationKind = 'active' | 'passive' | 'spell';
export type AbilityPresentationCategory = 'combat' | 'defense' | 'utility';

export interface AbilityPresentation {
  readonly id: string;
  readonly name: string;
  readonly shortLabel: string;
  readonly description: string;
  readonly category: AbilityPresentationCategory;
  readonly kind: AbilityPresentationKind;
  readonly iconBriefId?: string;
  readonly cooldownFrames?: number;
  readonly passiveEffectSummary?: string;
  readonly passiveRequirementSummary?: string;
}

export const ABILITY_PRESENTATION_BY_ID = {
  'battle-focus': {
    id: 'battle-focus',
    name: 'Battle Focus',
    shortLabel: 'FOCUS',
    description: 'Land enough hits to convert momentum into damage.',
    category: 'combat',
    kind: 'active',
    cooldownFrames: 30,
    iconBriefId: 'ability-icon-battle-focus',
  },
  'veteran-instinct': {
    id: 'veteran-instinct',
    name: 'Veteran Instinct',
    shortLabel: 'VETERAN',
    description: 'Constant battlefield awareness improves your armor and pickup range.',
    category: 'defense',
    kind: 'passive',
    iconBriefId: 'ability-icon-veteran-instinct',
  },
  'combat-flow': {
    id: 'combat-flow',
    name: 'Combat Flow',
    shortLabel: 'C.FLOW',
    description:
      'Sustained combat discipline yields permanent damage and attack-speed improvements.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +5%, Attack Speed +5%',
    iconBriefId: 'ability-icon-combat-flow',
  },
  'stalwart-resolve': {
    id: 'stalwart-resolve',
    name: 'Stalwart Resolve',
    shortLabel: 'STALWRT',
    description: 'Battle scars calcify into permanent armor and max HP.',
    category: 'defense',
    kind: 'passive',
    passiveEffectSummary: 'Armor +3, Max HP +15',
    iconBriefId: 'ability-icon-stalwart-resolve',
  },
  'ever-vigilant': {
    id: 'ever-vigilant',
    name: 'Ever Vigilant',
    shortLabel: 'VIGILANT',
    description: 'Constant evasion sharpens reflexes into a permanent speed advantage.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Move Speed +15%',
    iconBriefId: 'ability-icon-ever-vigilant',
  },
  'blade-mastery': {
    id: 'blade-mastery',
    name: 'Blade Mastery',
    shortLabel: 'BLADE',
    description: 'Bonus damage and accuracy while a slashing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%, Accuracy +0.05',
    passiveRequirementSummary: 'a slashing weapon',
    iconBriefId: 'ability-icon-blade-mastery',
  },
  'vital-targeting': {
    id: 'vital-targeting',
    name: 'Vital Targeting',
    shortLabel: 'VITAL',
    description: 'Bonus damage while a stabbing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%',
    passiveRequirementSummary: 'a stabbing weapon',
    iconBriefId: 'ability-icon-vital-targeting',
  },
  'brute-force': {
    id: 'brute-force',
    name: 'Brute Force',
    shortLabel: 'BRUTE',
    description: 'Bonus damage and armor while a smashing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%, Armor +2',
    passiveRequirementSummary: 'a smashing weapon',
    iconBriefId: 'ability-icon-brute-force',
  },
  'marksmans-eye': {
    id: 'marksmans-eye',
    name: "Marksman's Eye",
    shortLabel: 'MARKS',
    description: 'Bonus accuracy and projectile speed while a ranged weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Projectile Speed +10%',
    passiveRequirementSummary: 'a ranged weapon',
    iconBriefId: 'ability-icon-marksmans-eye',
  },
  'rapid-release': {
    id: 'rapid-release',
    name: 'Rapid Release',
    shortLabel: 'RAPID',
    description: 'Bonus attack speed while a throwing weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Attack Speed +20%',
    passiveRequirementSummary: 'a throwing weapon',
  },
  'iron-resolve': {
    id: 'iron-resolve',
    name: 'Iron Resolve',
    shortLabel: 'IRON',
    description: 'Bonus damage while a forearms weapon is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a forearms weapon',
  },
  'arcane-efficiency': {
    id: 'arcane-efficiency',
    name: 'Arcane Efficiency',
    shortLabel: 'ARCANE',
    description: 'Bonus damage while an arcane weapon is equipped.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'an arcane weapon',
  },
  'keen-swordsman': {
    id: 'keen-swordsman',
    name: 'Keen Swordsman',
    shortLabel: 'KEEN',
    description: 'Bonus accuracy and damage while a sword is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Damage +8%',
    passiveRequirementSummary: 'a sword',
  },
  shadowblade: {
    id: 'shadowblade',
    name: 'Shadowblade',
    shortLabel: 'SHADOW',
    description: 'Significant damage bonus while a dagger is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +20%',
    passiveRequirementSummary: 'a dagger',
  },
  'crushing-momentum': {
    id: 'crushing-momentum',
    name: 'Crushing Momentum',
    shortLabel: 'CRUSH',
    description: 'Bonus damage while a hammer is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +15%',
    passiveRequirementSummary: 'a hammer',
  },
  'athletes-grit': {
    id: 'athletes-grit',
    name: "Athlete's Grit",
    shortLabel: 'GRIT',
    description: 'Bonus accuracy and armor while sports equipment is equipped.',
    category: 'defense',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1, Armor +2',
    passiveRequirementSummary: 'sports equipment',
  },
  'archers-stance': {
    id: 'archers-stance',
    name: "Archer's Stance",
    shortLabel: 'ARCHER',
    description: 'Bonus accuracy while a bow is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Accuracy +0.1',
    passiveRequirementSummary: 'a bow',
  },
  'precision-bolts': {
    id: 'precision-bolts',
    name: 'Precision Bolts',
    shortLabel: 'PRECISE',
    description: 'Bonus damage while a crossbow is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a crossbow',
  },
  'hair-trigger': {
    id: 'hair-trigger',
    name: 'Hair Trigger',
    shortLabel: 'TRIGGER',
    description: 'Bonus attack speed while a pistol is equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Attack Speed +20%',
    passiveRequirementSummary: 'a pistol',
  },
  'juggling-arsenal': {
    id: 'juggling-arsenal',
    name: 'Juggling Arsenal',
    shortLabel: 'JUGGLE',
    description: 'Extra projectile while throwing weapons are equipped.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: '+1 projectile',
    passiveRequirementSummary: 'throwing weapons',
  },
  'bare-knuckle': {
    id: 'bare-knuckle',
    name: 'Bare Knuckle',
    shortLabel: 'KNUCKLE',
    description: 'Bonus damage while unarmed.',
    category: 'combat',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'no weapon (unarmed)',
  },
  'arcane-attunement': {
    id: 'arcane-attunement',
    name: 'Arcane Attunement',
    shortLabel: 'ARCANE',
    description: 'Bonus damage while a spellcraft weapon is equipped.',
    category: 'utility',
    kind: 'passive',
    passiveEffectSummary: 'Damage +10%',
    passiveRequirementSummary: 'a spellcraft weapon',
  },
  fireball: {
    id: 'fireball',
    name: 'Fireball',
    shortLabel: 'FIRE',
    description: 'Hurl a ball of fire that explodes in an area, burning enemies.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-fireball-v1',
    cooldownFrames: 300,
  },
  heal: {
    id: 'heal',
    name: 'Heal',
    shortLabel: 'HEAL',
    description: 'Mend your wounds with restorative magic.',
    category: 'defense',
    kind: 'spell',
    iconBriefId: 'ability-icon-heal-v1',
    cooldownFrames: 1800,
  },
  'pulse-shield': {
    id: 'pulse-shield',
    name: 'Pulse Shield',
    shortLabel: 'PULSE',
    description: 'Release a protective shockwave that knocks back nearby enemies.',
    category: 'defense',
    kind: 'spell',
    iconBriefId: 'ability-icon-pulse-shield-v1',
    cooldownFrames: 1200,
  },
  'magic-missile': {
    id: 'magic-missile',
    name: 'Magic Missile',
    shortLabel: 'MISSILE',
    description: 'Launch a precise arcane bolt into the nearest enemy.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-magic-missile',
    cooldownFrames: 180,
  },
  'frost-nova': {
    id: 'frost-nova',
    name: 'Frost Nova',
    shortLabel: 'FROST',
    description: 'Burst freezing magic around you, damaging and slowing nearby foes.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-frost-nova',
    cooldownFrames: 900,
  },
  bless: {
    id: 'bless',
    name: 'Bless',
    shortLabel: 'BLESS',
    description: 'Call down a brief blessing that sharpens your strikes and footwork.',
    category: 'utility',
    kind: 'spell',
    iconBriefId: 'ability-icon-bless',
    cooldownFrames: 1200,
  },
  stoneskin: {
    id: 'stoneskin',
    name: 'Stoneskin',
    shortLabel: 'STONE',
    description: 'Harden your flesh into living granite for a few desperate moments.',
    category: 'defense',
    kind: 'spell',
    iconBriefId: 'ability-icon-stoneskin',
    cooldownFrames: 1500,
  },
  curse: {
    id: 'curse',
    name: 'Curse',
    shortLabel: 'CURSE',
    description: 'Blight a cluster of enemies, dragging their movement into a crawl.',
    category: 'utility',
    kind: 'spell',
    iconBriefId: 'ability-icon-curse',
    cooldownFrames: 840,
  },
  'vampiric-touch': {
    id: 'vampiric-touch',
    name: 'Vampiric Touch',
    shortLabel: 'VAMP',
    description: 'Rip vitality from the nearest foe and pour it back into yourself.',
    category: 'combat',
    kind: 'spell',
    iconBriefId: 'ability-icon-vampiric-touch',
    cooldownFrames: 720,
  },
  haste: {
    id: 'haste',
    name: 'Haste',
    shortLabel: 'HASTE',
    description: 'Flood your limbs with quicksilver speed after a strong damage spike.',
    category: 'utility',
    kind: 'spell',
    iconBriefId: 'ability-icon-haste',
    cooldownFrames: 1080,
  },
} as const satisfies Readonly<Record<string, AbilityPresentation>>;

export function getAbilityPresentation(id: string): AbilityPresentation | undefined {
  return (ABILITY_PRESENTATION_BY_ID as Readonly<Record<string, AbilityPresentation>>)[id];
}
