<#
.SYNOPSIS
    Bootstrap .env.local with Azure OpenAI credentials for local development.

.DESCRIPTION
    Fetches credentials from the project's Azure OpenAI resource using the
    Azure CLI and writes them to .env.local (git-ignored).

    Cloud/CI environments are skipped automatically — use KeyVault or GitHub
    Secrets for those instead.

.NOTES
    Prerequisites:
        - Azure CLI installed  (https://aka.ms/install-azure-cli)
        - Logged in           (az login)
        - Owner/Contributor role on the rg-crawler-sprites resource group
#>

param(
    [switch]$Force   # Overwrite .env.local if it already exists
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# --- Cloud guard -----------------------------------------------------------
# CI runners and Copilot cloud agents provide credentials via GH Secrets or
# KeyVault. Do nothing and let those mechanisms work.
if ($env:CI -or $env:GITHUB_ACTIONS -or $env:CODESPACES) {
    Write-Host "Cloud/CI environment detected — skipping local env setup." `
        -ForegroundColor Cyan
    exit 0
}

# --- Already set up? -------------------------------------------------------
$envFile = Join-Path $PSScriptRoot '..' '.env.local' | Resolve-Path -ErrorAction SilentlyContinue
if (-not $envFile) {
    $envFile = Join-Path (Split-Path $PSScriptRoot) '.env.local'
}

if ((Test-Path $envFile) -and -not $Force) {
    Write-Host ".env.local already exists. Pass -Force to overwrite." `
        -ForegroundColor Yellow
    exit 0
}

# --- Azure config ----------------------------------------------------------
$subscription = '308f5463-c4b1-4cfb-94e9-c3e0fd0dc67c'
$resourceGroup = 'rg-crawler-sprites'
$accountName   = 'aoai-crawler-nalfeo'
$endpoint      = 'https://aoai-crawler-nalfeo.openai.azure.com/'
$deployment    = 'gpt-4o'

# --- Check az login --------------------------------------------------------
Write-Host "Checking Azure CLI login..." -ForegroundColor Cyan
$account = az account show --subscription $subscription 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "Not logged in to Azure. Run: az login" -ForegroundColor Red
    exit 1
}

# --- Fetch key -------------------------------------------------------------
Write-Host "Fetching API key from Azure..." -ForegroundColor Cyan
$apiKey = az cognitiveservices account keys list `
    --name $accountName `
    --resource-group $resourceGroup `
    --subscription $subscription `
    --query key1 -o tsv

if (-not $apiKey) {
    Write-Host "Failed to retrieve API key. Check your permissions." `
        -ForegroundColor Red
    exit 1
}

# --- Write .env.local ------------------------------------------------------
$repoRoot = Split-Path $PSScriptRoot
$outPath  = Join-Path $repoRoot '.env.local'

@"
# Local-only Azure OpenAI credentials — DO NOT COMMIT
# Generated by scripts/setup-azure-env.ps1
# Re-run this script on any new machine (requires: az login)
AZURE_OPENAI_ENDPOINT=$endpoint
AZURE_OPENAI_API_KEY=$apiKey
AZURE_OPENAI_VISION_DEPLOYMENT=$deployment
"@ | Set-Content $outPath -Encoding UTF8

Write-Host ".env.local written to: $outPath" -ForegroundColor Green
Write-Host "Run this script again with -Force to rotate the key." `
    -ForegroundColor DarkGray
