/**
 * Floor 3 UX Lab — Phaser sandbox for the Companion League onboarding,
 * starter-pick, and Trainer-poach surfaces (spec slice 12, UX surfaces #1–#3
 * in `docs/knowledge/game-design/floor3-companion-league.md` §15).
 *
 * Opens the real `ModalPickerUI` with the real presentation models from
 * `src/shared/floor3-ux.ts` — the same builders `MainGameScene` renders — so
 * copy, option rows, remaining recruit slots, and the party-lock warning can
 * be observed exactly as shipped. The starter/poach offers are generated by
 * the real seeded offer functions, so a given seed always shows the same
 * species in the same order.
 */
import GUI from 'lil-gui';
import Phaser from 'phaser';
import { GAME } from '../../shared/constants.js';
import { createModalPickerUI } from '../../engine/ModalPickerUI.js';
import { _generateStarterOffer, _generateTrainerPoachOffer } from '../../game/floor3Recruiting.js';
import { loadPetSpecies } from '../../shared/data/floor3/species.js';
import {
  buildFloor3FinalFourVersusModel,
  buildFloor3IntroModel,
  buildFloor3KeepCompanionPickerModel,
  buildFloor3PoachPickerModel,
  buildFloor3StarterPickerModel,
  buildFloor3StudioVersusModel,
} from '../../shared/floor3-ux.js';
import { createLogger } from '../../shared/logger.js';
import { SeededRandom } from '../../shared/random.js';
import { registerLab, type LabCategory } from '../registry.js';

type ControlsWithGui = HTMLElement & { __labGui?: GUI };

const LAB_ID = 'floor3-ux-lab';
const SCENE_KEY = 'Floor3UxLabScene';
const logger = createLogger('labs:floor3-ux');

/** Trainer roster size the poach picker previews (spec §6.2: 2–3 Companions). */
const POACH_ROSTER_SIZE = 3;

interface Floor3UxLabSettings {
  seed: number;
  /** Recruit slots left before the party locks — 1 shows the lock warning. */
  slotsRemaining: number;
  /** Level the previewed Trainer roster is fielded at. */
  trainerLevel: number;
}

function createFloor3UxLab(canvasHost: HTMLElement, controls: HTMLElement): () => void {
  const gui = (controls as ControlsWithGui).__labGui;
  if (!(gui instanceof GUI)) {
    throw new Error('Lab runner did not initialize lil-gui.');
  }

  const settings: Floor3UxLabSettings = { seed: 42, slotsRemaining: 5, trainerLevel: 12 };

  const root = document.createElement('div');
  root.style.cssText = 'position:relative;width:100%;height:100%;overflow:hidden;';
  canvasHost.append(root);

  const gameHost = document.createElement('div');
  gameHost.style.cssText = 'width:100%;height:100%;';
  root.append(gameHost);

  const hint = document.createElement('p');
  hint.textContent =
    'Floor 3 UX lab: open the rules briefing (#1), the seeded starter offer (#2), and the ' +
    'Trainer-poach picker (#3). Set "Slots remaining" to 1 to see the party-lock warning. ' +
    'Up/Down select, Enter confirm, Esc cancel.';
  hint.style.cssText = 'margin-top:16px;color:#c9d4ff;line-height:1.6;';
  controls.append(hint);

  let game: Phaser.Game | undefined;
  let picker: ReturnType<typeof createModalPickerUI> | undefined;

  const starterOffer = (): readonly string[] =>
    _generateStarterOffer(new SeededRandom(settings.seed)).map((species) => species.speciesId);

  const poachOffer = (): readonly string[] => {
    const rosterRng = new SeededRandom(settings.seed + 1);
    const trainerSpeciesIds = rosterRng
      .shuffle(loadPetSpecies().slice())
      .slice(0, POACH_ROSTER_SIZE)
      .map((species) => species.speciesId);
    return _generateTrainerPoachOffer(new SeededRandom(settings.seed + 2), trainerSpeciesIds).map(
      (species) => species.speciesId,
    );
  };

  const openIntro = (): void => {
    picker?.open(buildFloor3IntroModel(), {
      onConfirm: () => logger.info('Rules briefing acknowledged'),
    });
  };

  const openStarter = (): void => {
    picker?.open(buildFloor3StarterPickerModel(starterOffer()), {
      onConfirm: ({ option }) => logger.info('Starter picked', { speciesId: option.id }),
      onCancel: () => logger.info('Starter cancelled — defaults to option 0'),
    });
  };

  const openPoach = (): void => {
    picker?.open(
      buildFloor3PoachPickerModel({
        candidates: poachOffer().map((speciesId) => ({
          speciesId,
          level: settings.trainerLevel,
        })),
        slotsRemaining: settings.slotsRemaining,
        trainerName: 'Studio Ember',
      }),
      {
        onConfirm: ({ option }) => logger.info('Companion poached', { speciesId: option.id }),
        onCancel: () => logger.info('Poach cancelled — defaults to option 0'),
      },
    );
  };

  const openStudioVersus = (): void => {
    picker?.open(
      buildFloor3StudioVersusModel({
        id: 'emberforge',
        name: 'Emberforge Studio',
        affinity: 'ember',
        unlockLevel: 8,
        unlocked: true,
        defeated: false,
      }),
      { onConfirm: () => logger.info('Studio versus acknowledged') },
    );
  };

  const openFinalFourVersus = (): void => {
    picker?.open(
      buildFloor3FinalFourVersusModel(
        { handlerId: 'finalist-vega', handlerName: 'Vega Voltage', defeated: false },
        0,
        4,
      ),
      { onConfirm: () => logger.info('Final Four versus acknowledged') },
    );
  };

  const openBestInShow = (): void => {
    picker?.open(
      buildFloor3KeepCompanionPickerModel([
        {
          eid: 101,
          speciesId: 'ember-charger',
          currentName: 'Cinder Pup',
          ultimateName: 'Cinder Crown',
          level: 18,
          affinity: 'ember',
          fightingStyle: 'charger',
        },
        {
          eid: 102,
          speciesId: 'bloom-warden',
          currentName: 'Briar Guard',
          ultimateName: 'Verdant Bastion',
          level: 21,
          affinity: 'bloom',
          fightingStyle: 'warden',
        },
      ]),
      { onConfirm: ({ option }) => logger.info('Best in Show selected', { eid: option.id }) },
    );
  };

  class Floor3UxLabScene extends Phaser.Scene {
    constructor() {
      super({ key: SCENE_KEY });
    }

    create(): void {
      this.add.rectangle(0, 0, GAME.WIDTH, GAME.HEIGHT, 0x05070f).setOrigin(0, 0);
      this.add
        .text(GAME.WIDTH / 2, 40, 'Floor 3 UX Lab', {
          fontFamily: 'monospace',
          fontSize: '18px',
          color: '#4b5563',
        })
        .setOrigin(0.5, 0.5);

      picker = createModalPickerUI(this);
      openIntro();

      this.events.once('shutdown', () => {
        picker?.destroy();
        picker = undefined;
      });
    }
  }

  const createGame = (): void => {
    game?.destroy(true);
    const config: Phaser.Types.Core.GameConfig = {
      type: Phaser.AUTO,
      parent: gameHost,
      width: GAME.WIDTH,
      height: GAME.HEIGHT,
      backgroundColor: '#05070f',
      scene: [Floor3UxLabScene],
      scale: {
        mode: Phaser.Scale.FIT,
        autoCenter: Phaser.Scale.CENTER_BOTH,
      },
    };
    game = new Phaser.Game(config);
  };

  gui.add(settings, 'seed', 1, 9999, 1).name('Offer seed');
  gui.add(settings, 'slotsRemaining', 1, 5, 1).name('Slots remaining');
  gui.add(settings, 'trainerLevel', 1, 40, 1).name('Trainer roster level');
  gui.add({ intro: () => openIntro() }, 'intro').name('Open rules briefing (#1)');
  gui.add({ starter: () => openStarter() }, 'starter').name('Open starter picker (#2)');
  gui.add({ poach: () => openPoach() }, 'poach').name('Open poach picker (#3)');
  gui.add({ studio: () => openStudioVersus() }, 'studio').name('Open Studio versus (#10)');
  gui.add({ finals: () => openFinalFourVersus() }, 'finals').name('Open Final Four versus (#11)');
  gui.add({ winner: () => openBestInShow() }, 'winner').name('Open Best in Show (#12/#14)');
  gui.add({ restart: () => createGame() }, 'restart').name('Restart scene');

  createGame();

  return () => {
    picker?.destroy();
    game?.destroy(true);
    hint.remove();
    root.remove();
  };
}

registerLab(LAB_ID, {
  category: 'Meta' as LabCategory,
  name: 'Floor 3 UX Lab',
  description:
    'Companion League onboarding, starter-pick, and Trainer-poach modal surfaces (slice 12).',
  create: createFloor3UxLab,
});
