import fs from 'fs';
import { PNG } from 'pngjs';

const sprites = {
  player: [
    '................',
    '................',
    '.....bbbbbb.....',
    '...bbwwwwwwbb...',
    '..bwwwwwwwwwwb..',
    '..bwbbwwwwbbwb..',
    '..bwbwbwwbwbwb..',
    '..bwwwwwwwwwwb..',
    '...bbbbbbbbbb...',
    '.....yyyyyy.....',
    '....yyyyyyyy....',
    '...yy.yyyy.yy...',
    '...yy.yyyy.yy...',
    '......yyyy......',
    '.....y....y.....',
    '....bb....bb....',
  ],
  enemy_goblin: [
    '................',
    '................',
    '.....gggggg.....',
    '...gggggggggg...',
    '..ggkggggggkgg..',
    '..ggkggggggkgg..',
    '..gggggggggggg..',
    '...gggggggggg...',
    '.....rrrrrr.....',
    '....rrrrrrrr....',
    '...rr.rrrr.rr...',
    '...rr.rrrr.rr...',
    '......rrrr......',
    '.....r....r.....',
    '....bb....bb....',
    '................',
  ],
  enemy_orc: [
    '................',
    '....GGGGGGGG....',
    '..GGGGGGGGGGGG..',
    '.GGGGGGGGGGGGGG.',
    '.GGGGGGGGGGGGGG.',
    '.GGkkGGGGGGkkGG.',
    '.GGkkGGGGGGkkGG.',
    '.GGGGGGGGGGGGGG.',
    '..GGGGGGGGGGGG..',
    '....DDDDDDDD....',
    '...DDDDDDDDDD...',
    '...DD.DDDD.DD...',
    '...DD.DDDD.DD...',
    '......DDDD......',
    '.....D....D.....',
    '....bb....bb....',
  ],
  enemy_rat: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '......gttg......',
    '....ggttttgg....',
    '...gttwttwtg....',
    '..gttttttttt....',
    '..ggtttttttgg...',
    '...gtttttttgg...',
    '....gtttttggp...',
    '.....ggttg..p...',
    '......gggg..pp..',
    '............p...',
    '................',
  ],
  enemy_slime: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '......ssss......',
    '....ssssssss....',
    '...ssssssssss...',
    '..sswsksgsksss..',
    '..ssssssssssss..',
    '.ssssssssssssss.',
    '.ssssssssssssss.',
    '.ssssssssssssss.',
    '..ssssssssssss..',
    '................',
  ],
  enemy_boss: [
    '..GGGGGGGGGGGG..',
    '.GGGGGGGGGGGGGG.',
    '.GwwGGGGGGGGwwG.',
    'GwwwwGGGGGGwwwwG',
    'GwkkwwGGGGwwkkwG',
    'GwwkwwGGGGwwkwwG',
    'GwwwwGGGGGGwwwwG',
    '.GwwGGGGGGGGwwG.',
    '.GGGGGGGGGGGGGG.',
    '..GGGGGGGGGGGG..',
    '...GGGGGGGGGG...',
    '..GG.GGGGGG.GG..',
    '.GG..GGGGGG..GG.',
    '.G....GGGG....G.',
    '.G....GGGG....G.',
    'bb....bbbb....bb',
  ],
  npc_guide: [
    '................',
    '................',
    '.....wwwwww.....',
    '...wwwwwwwwww...',
    '..wwbbwwwwbbww..',
    '..wwbbwwwwbbww..',
    '..wwwwwwwwwwww..',
    '...wwwwwwwwww...',
    '.....bbbbbb.....',
    '....bbbbbbbb....',
    '...bb.bbbb.bb...',
    '...bb.bbbb.bb...',
    '......bbbb......',
    '.....b....b.....',
    '....ww....ww....',
    '................',
  ],
  item_gem: [
    '................',
    '................',
    '.......cc.......',
    '......cccc......',
    '.....cccccc.....',
    '....ccwwwwcc....',
    '...cccccccccc...',
    '....cccccccc....',
    '.....cccccc.....',
    '......cccc......',
    '.......cc.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  effect_proj: [
    '................',
    '................',
    '................',
    '................',
    '.......yy.......',
    '......yyyy......',
    '.....yyyyyy.....',
    '.....yywwyy.....',
    '.....yyyyyy.....',
    '......yyyy......',
    '.......yy.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  effect_enemy_proj: [
    '................',
    '................',
    '................',
    '................',
    '.......rr.......',
    '......rrrr......',
    '.....rrrrrr.....',
    '.....rrwwrr.....',
    '.....rrrrrr.....',
    '......rrrr......',
    '.......rr.......',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  effect_aoe: [
    '................',
    '......rrrr......',
    '....rrrrrrrr....',
    '...rrrrrrrrrr...',
    '..rrrrrrrwwrrr..',
    '..rrrrrrwwrrrr..',
    '.rrrrrrrrrrrrrr.',
    '.rrrrrwwrrrrrrr.',
    '.rrrrwwwrrrrrrr.',
    '.rrrrrrrrrrrrrr.',
    '..rrrrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '...rrrrrrrrrr...',
    '....rrrrrrrr....',
    '......rrrr......',
    '................',
  ],
  effect_enemy_aoe: [
    '................',
    '......ssss......',
    '....ssssssss....',
    '...ssssssssss...',
    '..ssssssswwsss..',
    '..sssssswwssss..',
    '.ssssssssssssss.',
    '.ssssswwsssssss.',
    '.sssswwwsssssss.',
    '.ssssssssssssss.',
    '..ssssssssssss..',
    '..ssssssssssss..',
    '...ssssssssss...',
    '....ssssssss....',
    '......ssss......',
    '................',
  ],
  weapon_returning: [
    '................',
    '.......c........',
    '......ccc.......',
    '.....ccccc......',
    '....cc...cc.....',
    '...cc.....cc....',
    '..cc.......cc...',
    '.cc.........cc..',
    '..cc.......cc...',
    '...cc.....cc....',
    '....cc...cc.....',
    '.....ccccc......',
    '......ccc.......',
    '.......c........',
    '................',
    '................',
  ],
  effect_melee: [
    '................',
    '.....wwwwww.....',
    '...wwwwwwwwww...',
    '..wwww....wwww..',
    '.www........www.',
    '.ww..........ww.',
    'ww............ww',
    'ww............ww',
    'ww............ww',
    'ww............ww',
    '.ww..........ww.',
    '.www........www.',
    '..wwww....wwww..',
    '...wwwwwwwwww...',
    '.....wwwwww.....',
    '................',
  ],
  effect_trap_arming: [
    '................',
    '.rrrrrrrrrrrrrr.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.r............r.',
    '.rrrrrrrrrrrrrr.',
    '................',
  ],
  effect_trap_armed: [
    '................',
    '.RRRRRRRRRRRRRR.',
    '.R............R.',
    '.R............R.',
    '.R............R.',
    '.R.....RR.....R.',
    '.R....RRRR....R.',
    '.R...RRRRRR...R.',
    '.R...RRRRRR...R.',
    '.R....RRRR....R.',
    '.R.....RR.....R.',
    '.R............R.',
    '.R............R.',
    '.R............R.',
    '.RRRRRRRRRRRRRR.',
    '................',
  ],
  effect_explosion: [
    '................',
    '...R.......R....',
    '..RRR.RRR.RRR...',
    '.RRRRRRRRRRRRR..',
    '...RRRRwRRRR....',
    '.RRRRRwRRwRRRR..',
    '..RRRRwwwRRRR...',
    '...RRRRwRRRRR...',
    '...RRRRwRRRR....',
    '..RRRRRwwRRRRR..',
    '.RRwRRRwwRRwRRR.',
    '..RRRRRwwRRRR...',
    '...RRRRRRRR.....',
    '....R.....R.....',
    '................',
    '................',
  ],
  effect_enemy_explosion: [
    '................',
    '...S.......S....',
    '..SSS.SSS.SSS...',
    '.SSSSSSSSSSSSS..',
    '...SSSSwSSSS....',
    '.SSSSSwSSwSSSS..',
    '..SSSSwwwSSSS...',
    '...SSSSwSSSSS...',
    '...SSSSwSSSS....',
    '..SSSSSwwSSSSS..',
    '.SSwSSSwwSSwSSS.',
    '..SSSSSwwSSSS...',
    '...SSSSSSSS.....',
    '....S.....S.....',
    '................',
    '................',
  ],
  effect_dead: [
    '................',
    '......wwwww.....',
    '.....wbbbbbww...',
    '....wbbbbbbbbw..',
    '...wbbbbbbbbbbw.',
    '...wbbbwwwbbbbw.',
    '..wbbbwkwkwbbbbw',
    '..wbbbwwwwwbbbbw',
    '..wbbbbwwwbbbbbw',
    '...wbbbbbbbbbbw.',
    '...wwbbbbbbbbw..',
    '.....wwwwwwww...',
    '......wwwww.....',
    '................',
    '................',
    '................',
  ],
};

// palette: color char -> [r,g,b,a]
const pal: Record<string, [number, number, number, number]> = {
  '.': [0, 0, 0, 0],
  b: [30, 30, 40, 255],
  w: [240, 240, 240, 255],
  k: [100, 100, 120, 255],
  y: [240, 180, 50, 255],
  g: [80, 180, 80, 255],
  G: [50, 130, 50, 255],
  r: [220, 60, 60, 255],
  R: [255, 40, 20, 255],
  D: [100, 60, 60, 255],
  t: [140, 130, 120, 255],
  p: [220, 130, 130, 255],
  s: [60, 210, 60, 220],
  S: [80, 240, 80, 230],
  c: [40, 220, 240, 255],
};

const keys = Object.keys(sprites);
const cols = keys.length;
const rows = 1;
const frameW = 16;
const frameH = 16;
const spacing = 1;

const png = new PNG({
  width: cols * frameW + (cols + 1) * spacing,
  height: rows * frameH + 2 * spacing,
});

for (let y = 0; y < png.height; y++) {
  for (let x = 0; x < png.width; x++) {
    const idx = (png.width * y + x) << 2;
    png.data[idx] = 0;
    png.data[idx + 1] = 0;
    png.data[idx + 2] = 0;
    png.data[idx + 3] = 0;
  }
}

keys.forEach((key, index) => {
  const col = index;
  const row = 0;
  const xBase = spacing + col * (frameW + spacing);
  const yBase = spacing + row * (frameH + spacing);
  const lines = sprites[key as keyof typeof sprites];

  for (let y = 0; y < frameH; y++) {
    const line = lines[y];
    for (let x = 0; x < frameW; x++) {
      const char = line[x];
      const color = pal[char] || pal['.'];
      const idx = (png.width * (yBase + y) + (xBase + x)) << 2;
      png.data[idx] = color[0];
      png.data[idx + 1] = color[1];
      png.data[idx + 2] = color[2];
      png.data[idx + 3] = color[3];
    }
  }
});

png.pack().pipe(fs.createWriteStream('public/assets/generated/custom-pixel-sprites.png'));
console.log('Generated public/assets/generated/custom-pixel-sprites.png with cols:', cols);
